version: "3.9"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    environment:
      - LANG=ru
      - WG_HOST=${WG_HOST}
      - PASSWORD=${WG_PASSWORD}
    container_name: wg-easy
    volumes:
      - /wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT:-51820}:51820/udp"
      - "${WG_WEB_PORT:-51821}:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: 85.92.108.236
    volumes:
      - /3x-ui/db/:/etc/x-ui/
      - /3x-ui/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped

volumes:
  wg-easy:
  3x-ui: